alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

alias tmux='tmux -2'

alias findr='find . -name'

alias grepr='grep -rn . -e'
alias grepri='grep -rni . -e'

# customtree() {
#     tree "$@"
#     eval "$(dircolors ~/.dircolors)"
# }

