alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

alias tmux='tmux -2'

alias gitlog="git --no-pager log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%a%D%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"

# customtree() {
#     tree "$@"
#     eval "$(dircolors ~/.dircolors)"
# }

