#!/usr/bin/env bash
# Note: intentionally does not use the bash-completions package.

# Completions are served by the ag-completion-service systemd socket service.
_query_completion_service() {
    local suggestions
    suggestions=$(printf '%s\n' "$COMP_LINE" | nc -N -U "$XDG_RUNTIME_DIR/ag-completion.sock" 2>/dev/null)

    if [[ -n "$suggestions" ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$suggestions" -- "${COMP_WORDS[COMP_CWORD]}")
    fi
}

complete -F _query_completion_service ag

# Completions for setscreen command
_get_screen_layouts ()
{
    local home=`echo ~`
    local scripts=(~/.screenlayout/*)
    COMPREPLY=()

    local cur=${COMP_WORDS[COMP_CWORD]}

    for script in ${scripts[@]}; do
        local script_reduced=`echo $script | sed "s@$home/\.screenlayout/\(\w\+\)\.sh@\1@"`
        if [[ $script_reduced == $cur* ]]; then
            COMPREPLY+=( $script_reduced )
        fi
    done

    return 0
}

complete -F _get_screen_layouts setscreen
